[tox]
envlist = lint,pytest
skipsdist = false

[gh-actions]
python =
  3.12: pytest, lint

[testenv]
basepython = python3
package = wheel
wheel_build_env = .pkg

[testenv:pytest]
deps =
  -rrequirements-dev.txt
commands =
  pytest --verbose                 \
         --strict                  \
         --cov=girder_jsonforms    \
         --cov-report=xml          \
         -n {env:PYTEST_XDIST_N:4} \
         {posargs}

[testenv:lint]
skip_install = true
skipdist = true
deps =
  ruff
commands =
  ruff check .

[tool:pytest]
cache_dir = build/test/pytest_cache
junit_family = xunit2
testpaths = test
